### ISSUE TITLE
인테리어 계획

### ISSUE THREAD

**Issue by JSpiner** [JSpiner/24#5]

**Comment by SlZeroth** [comment]
- 벽걸이 TV
- PS4
- 세이버 쿠션

**Comment by omjoonkim** [comment]
> 바를 만든다

**Comment by JSpiner** [comment]
- [x] 홈 칵테일 바
- [x] 빔프로젝터 / 스크린
- [x] 업무용 책상
- [x] 침대
- [x] 도배 or 페인트
- [x] 음성제어 IoT
- [x] 피아노

**Comment by omjoonkim** [comment]
+ 손님방

**Comment by JSpiner** [comment]
### 침대
이층침대를 유지할지, 새로운 침대를 구할지 결정해야함.

**Comment by JSpiner** [comment]
## 음성제어 IoT
- 릴레이
- 아두이노 미니 / 와이파이모듈

10개씩 구매 완료

**Comment by JSpiner** [comment]
실측정 단면도

<img width="429" alt="2018-07-15 5 14 26" src="https://user-images.githubusercontent.com/5474864/42731990-5301168e-8853-11e8-88b1-f41cd35610e5.png">

**Comment by JSpiner** [comment]
<img width="416" alt="2018-07-22 8 47 40" src="https://user-images.githubusercontent.com/5474864/43045272-86fcf6d6-8df0-11e8-9b01-37869e8a0849.png">

인테리어 초안1

**Comment by JSpiner** [comment]
### 구매목록 

위치 | 품목
-- | --
출입구 |  
  | 우산꽂이
  | 전신거울
  | 액자 2~3개
  | 스마트미러
  | 조립식타일
큰방 |  
  | 침대(슈퍼싱글)
  | 침대협탁
  | 웜톤스탠드
  | 공기청정기
  | 옷장(행거 X)
  | 벽선반
거실 |  
  | 소파
  | 빔프로젝터
  | 천장형스크린
  | 홈바테이블
  | 중형화분 2분
  | 암막 블라인드
작은방 |  
  | 1200 책상
  | 1600 책상
  | 공기청정기
  | 피아노
  | 총기거치
  | 깔끔한 스타일 의자 2개

**Comment by eastroots92** [comment]
ㄱㅏ전은 엘지

**Comment by JSpiner** [comment]
home iot에 대한 상세내용은 
https://github.com/JSpiner/HomeIoT 에서 처리될 예정

**Comment by wplong11** [comment]
끝?

**Comment by JSpiner** [comment]
끝. 프로젝터 및 홈IoT 설계는 다른 이슈에서 처리예정
